# Generated by Django 4.2.6 on 2023-10-15 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("informasi_kesehatan", models.CharField(max_length=100)),
                ("tinggi_badan", models.PositiveIntegerField()),
                ("berat_badan", models.PositiveIntegerField()),
                ("golongan_darah", models.CharField(max_length=2)),
                ("catatan_kejahatan", models.CharField(max_length=255)),
                ("nama_user", models.CharField(max_length=60)),
                ("jenis_kelamin", models.CharField(max_length=1)),
                ("kewarganegaraan", models.CharField(max_length=50)),
                ("agama", models.CharField(max_length=32)),
                ("is_kawin", models.BooleanField()),
                ("user_email_user", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
