# Generated by Django 4.2.6 on 2023-10-16 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profil", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profil",
            old_name="user",
            new_name="user_id_user",
        ),
    ]
