# Generated by Django 4.2.6 on 2023-10-16 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profil", "0002_rename_user_profil_user_id_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profil",
            name="user_id_user",
        ),
        migrations.AlterField(
            model_name="profil",
            name="is_kawin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profil",
            name="user_email_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
