# Generated by Django 4.2.6 on 2023-10-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profil", "0005_alter_profil_gambar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profil",
            name="jenis_kelamin",
            field=models.CharField(
                choices=[("l", "Laki-Laki"), ("p", "Perempuan")], max_length=1
            ),
        ),
    ]
