# Generated by Django 4.2.6 on 2023-10-17 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profil", "0006_alter_profil_jenis_kelamin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profil",
            options={"permissions": [("view_profil_images", "Can view Profil images")]},
        ),
    ]
