# Generated by Django 4.2.6 on 2023-10-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("id_card", "0003_alter_id_card_gambar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="id_card",
            name="gambar",
            field=models.ImageField(upload_to="id_cards"),
        ),
    ]
