# Generated by Django 4.2.6 on 2023-10-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postingan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postingan",
            name="waktu_upload",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
