# Generated by Django 4.2.6 on 2023-10-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postingan", "0003_alter_postingan_id_postingan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postingan",
            name="is_public",
        ),
    ]
