# Generated by Django 4.2.6 on 2023-10-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lampiran", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lampiran",
            name="id_lampiran",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
