# Generated by Django 4.2.6 on 2023-10-17 05:46

from django.db import migrations, models
import lampiran.models


class Migration(migrations.Migration):

    dependencies = [
        ("lampiran", "0002_alter_lampiran_id_lampiran"),
    ]

    operations = [
        migrations.AddField(
            model_name="lampiran",
            name="key",
            field=models.UUIDField(
                default=lampiran.models.Lampiran.generate_custom_uuid, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="lampiran",
            name="dokumen_laporan",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=lampiran.models.Lampiran.unique_filename,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lampiran",
            unique_together={("key", "id_lampiran")},
        ),
    ]
