# Generated by Django 4.2.6 on 2023-10-17 12:27

from django.db import migrations, models
import lampiran.models


class Migration(migrations.Migration):

    dependencies = [
        ("lampiran", "0003_lampiran_key_alter_lampiran_dokumen_laporan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lampiran",
            name="key_crypto",
            field=models.CharField(
                default=lampiran.models.Lampiran.generate_custom_uuid,
                editable=False,
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lampiran",
            name="pro_crypto",
            field=models.CharField(
                default=lampiran.models.Lampiran.generate_custom_uuid,
                editable=False,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lampiran",
            name="key",
            field=models.CharField(
                default=lampiran.models.Lampiran.generate_custom_uuid,
                editable=False,
                max_length=32,
            ),
        ),
    ]
