# Generated by Django 4.2.6 on 2023-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lampiran", "0004_lampiran_key_crypto_lampiran_pro_crypto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lampiran",
            name="metode_crypto",
            field=models.CharField(
                choices=[
                    ("aes-csb", "AES-CBC"),
                    ("aes-cfb", "AES-CFB"),
                    ("aes-ofb", "AES-OFB"),
                    ("aes-ctr", "AES-CTR"),
                    ("rc4-txt", "RC4 TEXT"),
                    ("rc4-img", "RC4 FILE"),
                    ("des-csb", "DES-CBC"),
                    ("des-cfb", "DES-CFB"),
                    ("des-ofb", "DES-OFB"),
                    ("des-ctr", "DES-CTR"),
                ],
                default="aes-csb",
                max_length=10,
            ),
        ),
    ]
