# Generated by Django 4.2.6 on 2023-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lampiran", "0006_alter_lampiran_dokumen_laporan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lampiran",
            name="dokumen_laporan",
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
